name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        mongodb-version: ['4.0', '4.2', '4.4']

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.6.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        mongodb-replica-set: test-rs
        mongodb-port: 27017

    - name: Generate Environment Variables File for Production
      run: |
          echo "MONGO_URI=$MONGO_URI" >> .env.production
          echo "SECRETKEY=$SECRETKEY" >> .env.production
          echo "API_KEY=$API_KEY" >> .env.production
          echo "PORT=$PORT" >> .env.production
      env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          SECRETKEY: ${{ secrets.SECRETKEY }}
          API_KEY: ${{ secrets.API_KEY}}
          PORT: ${{ secrets.PORT }}


    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm start
      env:
        CI: true
