name: Run tests

on: 
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        mongodb-version: ['4.4']

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.6.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        mongodb-replica-set: test-rs
        mongodb-port: 27017

    - name: Install dependencies
      run: npm install

    - name: start server
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
        SECRETKEY: ${{ secrets.SECRETKEY }}
        API_KEY: ${{ secrets.API_KEY}}
        PORT: ${{ secrets.PORT }}
        CI: true
      run: npm start
